### ISSUE TITLE
Checkbox Renderer Header Checkbox do not work

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#100]
Because of the declared return type of ":boolean" of the render method declared inside vidi_frontend/Classes/ViewHelpers/Grid/Column/HeaderViewHelper.php the output of the header checkbox to select a whole row does not work.
Instead of a checkbox the number "1" appears.

**Comment by fabarea** [comment]
It should be a string. I fixed that in https://github.com/fabarea/vidi_frontend/commit/e8d7014062f788f6fc6c59d516e3179fea6edb51
