### ISSUE TITLE
Additional equals "in" not working under v3.0.1

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#103]
After updating vidi_frontend from v2.1.1 to v3.0.1 additional equals "in" are not working anymore.

To reproduce add an additional equals to the frontend plugin like:
pid in 1,2,3

btw.: under v2.1.1 is was also possible to write the same restriction as "pid in (1,2,3)" which is not working under v3.0.1 because of line 146 in the matcher factory:
```
$matcher->$operator($operand, GeneralUtility::trimExplode(',', $value, true));
```
Changing this line to the following, would enable it again:
```
$matcher->$operator($operand, GeneralUtility::trimExplode(',', trim($value, '()'), true));
```
But this it not the reason of this issue.

I think it stucts somewhere deeper in the vidi db backend.
Maybe inside the fetchResults method, which overhand *no types* to the execute query method.

[EDIT]
After doing some more research I'm sure that the missing type definition of the executeQuery call inside the fetchResults method is the reason for the problem.

If I change the call of the upper example (pid in 1,2,3) from this:
```
$rows = $this->getConnection()->executeQuery($sql, $parameters)->fetchAll();
```
to this:
```
$rows = $this->getConnection()->executeQuery($sql, $parameters, [\Doctrine\DBAL\Connection::PARAM_INT_ARRAY])->fetchAll();
```
I get the expected result.
Currently I have no glue how to get this feature working for all cases, because the values could be strings and integers and arrays of strings and integers as well.

**Comment by mediaessenz** [comment]
I developed a working solution for the problem.
Maybe you like my aproach:
```
        $types = [];
        foreach ($parameters as $parameter) {
            if (is_array($parameter)) {
                if (MathUtility::canBeInterpretedAsInteger($parameter[0])) {
                    $types[] = \Doctrine\DBAL\Connection::PARAM_INT_ARRAY;
                } else {
                    $types[] = \Doctrine\DBAL\Connection::PARAM_STR_ARRAY;
                }
            } else {
                if (MathUtility::canBeInterpretedAsInteger($parameter)) {
                    $types[] = ParameterType::INTEGER;
                } else {
                    $types[] = ParameterType::STRING;
                }
            }
        }

        $rows = $this->getConnection()
            ->executeQuery($sql, $parameters, $types)
            ->fetchAll();
```

**Comment by mediaessenz** [comment]
Index: Classes/Persistence/Storage/VidiDbBackend.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Classes/Persistence/Storage/VidiDbBackend.php	(date 1591733909063)
+++ Classes/Persistence/Storage/VidiDbBackend.php	(date 1591733909063)
@@ -9,12 +9,14 @@
  * LICENSE.md file that was distributed with this source code.
  */
 
+use Doctrine\DBAL\ParameterType;
 use Fab\Vidi\Persistence\Query;
 use Fab\Vidi\Utility\BackendUtility;
 use TYPO3\CMS\Core\Database\Connection;
 use TYPO3\CMS\Core\Database\ConnectionPool;
 use TYPO3\CMS\Core\Database\Query\QueryBuilder;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
+use TYPO3\CMS\Core\Utility\MathUtility;
 use TYPO3\CMS\Core\Versioning\VersionState;
 use TYPO3\CMS\Extbase\Persistence\Generic\Exception;
 use TYPO3\CMS\Extbase\Persistence\Generic\Qom\ComparisonInterface;
@@ -83,6 +85,31 @@
         $this->query = $query;
     }
 
+    /**
+     * @param $parameters
+     * @return array
+     */
+    protected static function getTypes($parameters)
+    {
+        $types = [];
+        foreach ($parameters as $parameter) {
+            if (is_array($parameter)) {
+                if (MathUtility::canBeInterpretedAsInteger($parameter[0])) {
+                    $types[] = \Doctrine\DBAL\Connection::PARAM_INT_ARRAY;
+                } else {
+                    $types[] = \Doctrine\DBAL\Connection::PARAM_STR_ARRAY;
+                }
+            } else {
+                if (MathUtility::canBeInterpretedAsInteger($parameter)) {
+                    $types[] = ParameterType::INTEGER;
+                } else {
+                    $types[] = ParameterType::STRING;
+                }
+            }
+        }
+        return $types;
+    }
+
     /**
      * Returns the result of the query
      */
@@ -95,7 +122,7 @@
         //print $sql; exit();
 
         $rows = $this->getConnection()
-            ->executeQuery($sql, $parameters)
+            ->executeQuery($sql, $parameters, self::getTypes($parameters))
             ->fetchAll();
 
         return $this->getContentObjects($rows);
@@ -111,6 +138,7 @@
         $parameters = [];
         $statementParts = $this->parseQuery($parameters);
         $statementParts = $this->processStatementStructureForRecursiveMMRelation($statementParts);
+        $types = self::getTypes($parameters);
 
         // if limit is set, we need to count the rows "manually" as COUNT(*) ignores LIMIT constraints
         if (!empty($statementParts['limit'])) {
@@ -118,7 +146,7 @@
 
             $count = $this
                 ->getConnection()
-                ->executeQuery($sql, $parameters)
+                ->executeQuery($sql, $parameters, $types)
                 ->rowCount();
         } else {
             $statementParts['fields'] = array('COUNT(*)');
@@ -133,7 +161,7 @@
             $sql = $this->buildQuery($statementParts);
             $count = $this
                 ->getConnection()
-                ->executeQuery($sql, $parameters)
+                ->executeQuery($sql, $parameters, $types)
                 ->fetchColumn(0);
         }
         return (int)$count;

**Comment by fabarea** [comment]
Hi Alexander. Thanks for digging into that issue. 

Yes, we can introduce this check PARAM_INT_ARRAY vs PARAM_STR_ARRAY. If you create a PR in Vidi, I will gladly merge it.

**Comment by mediaessenz** [comment]
Here we go: https://github.com/fabarea/vidi/pull/195

**Comment by fabarea** [comment]
Thanks! 🥇
