### ISSUE TITLE
because of missing pid in generated ajax url, I get an error 500

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#25]
The error message is not very help full:
```
#1297759968: Exception while property mapping at property path "":Vidi Frontend: I could not access this resource
```
To reproduce:
- enable realurl
- config.prefixLocalAnchors = all
- config.baseURL = http://dev.vm/ (in my case)
- add the plugin on a *subpage*
- configure plugin to show e.g. frontend users and ajax loading

If open up this page in frontend, no feusers are loaded.
In the network monitor you will see a call like this:
```
http://dev.vm/?type=1416239670&dataType=fe_users&identifier=8020&format=jso…ntend_pi1%5BcontentData%5D=8020&tx_vidifrontend_pi1%5BsearchTerm%5D=%5B%5D
```
But it should be something like this:
```
http://dev.vm/subpage/?type=1416239670&dataType=fe_users&identifier=8020&format=jso…ntend_pi1%5BcontentData%5D=8020&tx_vidifrontend_pi1%5BsearchTerm%5D=%5B%5D
```
As you see, the path "subpage" or the parameter "?id=123" is missing in ajax call.
Due to this problem, the content element (the plugin) is not found (because it is not placed on the root page) and the described error is thrown.

**Comment by fabarea** [comment]
Can you test if master fix the issue? It did for me at least.

**Comment by mediaessenz** [comment]
Yes, it seems to work now.
But I only add window.location.pathname +  in front of all ajaxSource settings (including min-files) in my local files by hand and do not checked out / testet the current master version.
