### ISSUE TITLE
results per page of ajax view is not working anymore

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#70]
After updating to latest master the ajax view alway show all entries and ignores result per page setting.

**Comment by fabarea** [comment]
Can you comment [this line](https://github.com/fabarea/vidi_frontend/blob/master/Classes/Controller/ContentController.php#L147) and see if that fixes. I introduced `$pager->setLimit(0)` to respect the limit that you can set in the plugin settings (Backend) but it could have a side effect...

**Comment by mediaessenz** [comment]
commenting this line fixes the problem
