### ISSUE TITLE
ajax calls with cHash parameters do not work since update TYPO3 to 7.6.11

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#71]
instead a page not found exception is thrown

**Comment by fabarea** [comment]
A Vidi exception our Core exception? Could you provide with more detail?

**Comment by mediaessenz** [comment]
Its a page not found error, who comes from the core, because of an invalid cHash

To reproduce the problem:
Place a plugin, which is using cHash, on a different page than vidi_frontend (in ajax mode).
Add a $this->forward() call from this page to the page containing the vidi_frontend plugin.
If this url contains a cHash, the ajax call of vidi_frontend fails.

**Comment by fabarea** [comment]
I wouldn't know how to fix that. Let me know if you've got tracks of something.

**Comment by mediaessenz** [comment]
I found a solution/workaround inside VidiFrontend.Grid.js line 124:
```
			// Add loading by ajax handler
			if (settings.loadContentByAjax) {
				// Modifiziert von Alexander Grein deleteQueryParam('cHash') hinzugefügt
				var uri = new Uri(window.location.pathname).deleteQueryParam('cHash').addQueryParam('type', '1416239670');
				options.ajax = {
					url: settings.loadContentByAjax ? uri : '',
					data: function(data) {

						// Get the parameter related to filter from the URL and "re-inject" them into the Ajax request
						var uri = new Uri(window.location.href).deleteQueryParam('cHash');
....
```
