### ISSUE TITLE
Pagebrowser is not working correctly

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#74]
The pagebrowser is still not working.

If you have e.g. 30 records and set "Max limit of records (0 means not limit)" to 0 you will get all 30 records in frontend, independent of the selected records per page in frontend.

**Comment by fabarea** [comment]
Rrr... sorry. The offset was still wrong. That way it works for me in Ajax mode. Let me know if not for you. I am not really sure if it is what you described.
