### ISSUE TITLE
Pagebrowser in ajax mode is not working correctly

### ISSUE THREAD

**Issue by mediaessenz** [fabarea/vidi_frontend#75]
With this setting:
<img width="511" alt="bildschirmfoto 2016-10-22 um 16 21 41" src="https://cloud.githubusercontent.com/assets/16038153/19620012/169f02b2-9874-11e6-9d70-a38e79ebd002.png">
I get this output:
<img width="951" alt="bildschirmfoto 2016-10-22 um 16 21 12" src="https://cloud.githubusercontent.com/assets/16038153/19620018/2c8f2bec-9874-11e6-99de-0599adfbf918.png">

And with this setting:
<img width="509" alt="bildschirmfoto 2016-10-22 um 16 22 56" src="https://cloud.githubusercontent.com/assets/16038153/19620022/38412a8a-9874-11e6-8b51-9b05a6b32e5f.png">
I get this output:
<img width="954" alt="bildschirmfoto 2016-10-22 um 16 22 36" src="https://cloud.githubusercontent.com/assets/16038153/19620024/43b88372-9874-11e6-8caf-a88acbc82ca9.png">

In both cases I use this settings in the plugin:
<img width="631" alt="bildschirmfoto 2016-10-22 um 16 23 07" src="https://cloud.githubusercontent.com/assets/16038153/19620027/52e9446c-9874-11e6-98b6-e1aa09ad9747.png">

If you look at the "View" (german: "Zeige") settings in the frontend in both cases, you will see that the pagebrowser in ajax mode is not working correctly.

**Comment by mediaessenz** [comment]
Any news about this issue?

**Comment by fabarea** [comment]
No, I didn't have time to further dig. Your steps to reproduce the issue are clear, though. However, I am a bit voiceless since I had this scenario in one of our instance and didn't meet the bug. Perhaps it wasn't exactly like that after all. From memory...

This must not be so hard to fix, though. Could you open your ajax request and see what is wrong in 
https://github.com/fabarea/vidi_frontend/blob/master/Classes/Controller/ContentController.php#L142. I would appreciate.

**Comment by mediaessenz** [comment]
I can not believe that this ever has worked, since the get parameter "length" is not considered in the listAction of the contentController.

Anyway, if you add this few lines to this action (just before you check if limit is an empty string) the limitation should work also for ajax mode:

```
$length = GeneralUtility::_GET('length');
		if ($length !== null && MathUtility::canBeInterpretedAsInteger($length)) {
            $length = (int)$length;
            if ($length > -1) {
                $settings['limit'] = $length;
            }
        }
```

Don't forget `use TYPO3\CMS\Core\Utility\MathUtility;` at top.
