### ISSUE TITLE
Include TS: Wrong condition and wrong description

### ISSUE THREAD

**Issue by andre-spindler** [fabarea/vidi_frontend#79]
$configuration['autoload_typoscript'] is not an array and doesn't has a key 'value'.
In both conditions ['value'] hs to be removed.

in addition the description in ext_conf_template.txt is wrong:
Cite: "If enabled, the extension will automatically load the TypoScript setup that is required. When un-checking make sure to include / load the TypoScript on your own as a Static TypoScript."
But the behaviour is to enable the typoscript as tatic template when checked and to do nothing if not.

**Comment by fabarea** [comment]
Could you make a PR to improve the situation?

**Comment by mediaessenz** [comment]
I think this issue is already fixed
