### ISSUE TITLE
Example add tt_address to vidi_frontend

### ISSUE THREAD

**Issue by ghwaldo** [fabarea/vidi_frontend#99]
Hi there,
i'm trying to build a list for tt_address with vidi_frontend on TYPO3 V9.5.

I cleared the list of available datatables in extension config. now i can choose everey table.

As long as i choose fe_user or fe_groups i get valid outputs.

if i try tt_address as source in plugin config i get errors similar to

Oops, an error occurred! Code: 20190417110608c46b7283.

Can you help on to the right way ? do i have to add tt_address somewhere else ?

**Comment by fabarea** [comment]
Could you check (install?) this tt_address which includes a Vidi BE module

https://github.com/Ecodev/tt_address

This is the version we are using.
